server:
  port: 8080
spring:
  application:
    name: orderservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: 111111

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients: userservice    #指定对userservice这个服务饥饿加载
feign:
  client:
    config:
      default: # default全局的配置
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
    #clients，是个集合，如果需要多个就要写成
    #clients:
    #    -userservice
    #    -xxservice